version: "3.9"

services:

  db:
    image: postgres:16.1
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: muzycznysklep
      POSTGRES_USER: muzycznysklep
      POSTGRES_PASSWORD: muzycznysklep
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
    - 6379:6379
